services:
  dw:
    image: postgres:14
    environment:
      POSTGRES_USER: dw
      POSTGRES_PASSWORD: dw12345
      POSTGRES_DB: dw
  
  airflow:
    build: ./airflow
    command: standalone
    ports:
      - 8080:8080
    environment:
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}