services:
  dw:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dw
      POSTGRES_PASSWORD: dw12345
      POSTGRES_DB: dw
  
  airflow:
    build: ./dockerfiles/airflow
    command: bash -c "airflow db migrate && airflow users create --username airflow --firstname airflow --lastname airflow --role Admin --email airflow@airflow --password airflow && airflow standalone"
    ports:
      - 8080:8080
    volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
